# Generated by Django 4.2.27 on 2026-01-11 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolgroups', '0004_add_access_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('join_request_created', 'Join Request Created'), ('join_request_accepted', 'Join Request Accepted'), ('join_request_denied', 'Join Request Denied'), ('role_changed', 'Role Changed'), ('ticket_closed', 'Ticket Closed'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_resolved', 'Ticket Resolved'), ('article_published', 'Article Published'), ('article_unpublished', 'Article Unpublished'), ('settings_changed', 'Settings Changed')], help_text='Type of action performed', max_length=50)),
                ('resource_type', models.CharField(help_text='Type of resource affected (e.g., "JoinRequest", "Ticket", "User")', max_length=100)),
                ('resource_id', models.IntegerField(help_text='ID of the affected resource')),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data (JSON object)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('school_group', models.ForeignKey(blank=True, help_text='Organization context for this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='schoolgroups.schoolgroup')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='audit_audit_action__eafc67_idx'), models.Index(fields=['school_group', 'created_at'], name='audit_audit_school__bbc6c8_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx')],
            },
        ),
    ]
