# Generated by Django 4.2.27 on 2026-01-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolgroups', '0003_alter_schoolgroup_options_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_organization',
            field=models.ForeignKey(blank=True, help_text='Currently active organization for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='schoolgroups.schoolgroup'),
        ),
    ]
