# Generated by Django 4.2.27 on 2026-01-09 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('schoolgroups', '0004_add_access_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ticket title', max_length=255)),
                ('description', models.TextField(help_text='Ticket description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the ticket', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the ticket', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Resolution notes added when ticket is resolved', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When ticket was marked as resolved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When ticket was closed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin assigned to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('chat', models.OneToOneField(blank=True, help_text='Chat this ticket was escalated from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='chats.chat')),
                ('school_group', models.ForeignKey(help_text='Organization this ticket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='schoolgroups.schoolgroup')),
                ('user', models.ForeignKey(help_text='User who created the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tickets_tic_user_id_ee01b8_idx'), models.Index(fields=['school_group', 'status'], name='tickets_tic_school__6a8b24_idx'), models.Index(fields=['assigned_to', 'status'], name='tickets_tic_assigne_e36302_idx'), models.Index(fields=['status', 'priority'], name='tickets_tic_status_b256f6_idx')],
            },
        ),
    ]
