# Generated by Django 4.2.28 on 2026-03-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('portal', 'Portal'), ('chat', 'Chat'), ('other', 'Other')], default='portal', help_text='Where this ticket was created (portal, chat, etc.)', max_length=20),
        ),
    ]
