# Generated by Django 4.2.28 on 2026-02-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolgroups', '0006_unlock_free_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g. USB-C Hub)', max_length=255)),
                ('location', models.CharField(help_text='Where it is stored (e.g. Closet A, Room 101)', max_length=255)),
                ('item_number', models.CharField(help_text='SKU / part number', max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Optional serial number', max_length=255)),
                ('buy_link', models.URLField(blank=True, help_text='Optional link to purchase / reorder')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Quantity on hand')),
                ('min_stock', models.PositiveIntegerField(default=0, help_text='Low-stock threshold; 0 = no alert')),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_group', models.ForeignKey(help_text='Organization this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='schoolgroups.schoolgroup')),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
                'ordering': ['location', 'name'],
            },
        ),
    ]
