# Generated by Django 4.2.27 on 2026-01-11 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolgroups', '0004_add_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=255)),
                ('content', models.TextField(help_text='Article content')),
                ('category', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('account', 'Account'), ('billing', 'Billing'), ('other', 'Other')], default='general', help_text='Article category', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Article tags (array of strings)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Article status', max_length=20)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times article has been viewed')),
                ('helpful_votes', models.IntegerField(default=0, help_text='Number of helpful votes')),
                ('published_at', models.DateTimeField(blank=True, help_text='When article was published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who created this article', on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('school_group', models.ForeignKey(blank=True, help_text='Organization this article belongs to (null for global articles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='schoolgroups.schoolgroup')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'school_group'], name='knowledge_a_status_6b43b0_idx'), models.Index(fields=['category', 'status'], name='knowledge_a_categor_5fa317_idx'), models.Index(fields=['school_group', 'status'], name='knowledge_a_school__86702d_idx')],
            },
        ),
    ]
