# Generated by Django 4.2.27 on 2026-01-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the organization')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the organization is active')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', help_text='Subscription plan for this organization', max_length=20)),
                ('admin_limit', models.IntegerField(default=1, help_text='Maximum number of admins allowed (1 for Free, 10 for Pro, custom for Enterprise)')),
                ('ai_enabled', models.BooleanField(default=False, help_text='Whether AI Add-On is enabled')),
                ('ai_plan', models.CharField(choices=[('limited', 'Limited'), ('unlimited', 'Unlimited')], default='limited', help_text='AI assistance level: limited or unlimited', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Group',
                'verbose_name_plural': 'School Groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
