# Generated by Django 4.2.27 on 2026-01-06 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolgroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', help_text='Membership status', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, help_text='When the user was accepted into the group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_group', models.ForeignKey(help_text='School group the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schoolgroups.schoolgroup')),
                ('user', models.ForeignKey(help_text='User who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Group Membership',
                'verbose_name_plural': 'School Group Memberships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='schoolgroup_user_id_d17d78_idx'), models.Index(fields=['school_group', 'status'], name='schoolgroup_school__038aef_idx')],
                'unique_together': {('user', 'school_group')},
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', help_text='Request status', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the request was made')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about the request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
                ('school_group', models.ForeignKey(help_text='School group being requested', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='schoolgroups.schoolgroup')),
                ('user', models.ForeignKey(help_text='User requesting to join', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Join Request',
                'verbose_name_plural': 'Join Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['school_group', 'status'], name='schoolgroup_school__8f792d_idx'), models.Index(fields=['user', 'status'], name='schoolgroup_user_id_ccbb9c_idx')],
            },
        ),
    ]
