# Generated by Django 4.2.27 on 2026-01-06 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolgroups', '0002_schoolgroupmembership_joinrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolgroup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='schoolgroupmembership',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization Membership', 'verbose_name_plural': 'Organization Memberships'},
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
