# Generated by Django 4.2.27 on 2026-01-07 17:10

from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta
import random
import string


def generate_access_code_for_existing_orgs(apps, schema_editor):
    """Generate access codes for existing organizations."""
    SchoolGroup = apps.get_model('schoolgroups', 'SchoolGroup')
    
    # Generate 12-character code using uppercase letters and digits
    # Exclude confusing characters: 0, O, I, 1
    characters = string.ascii_uppercase + string.digits
    characters = characters.replace('0', '').replace('O', '').replace('I', '').replace('1', '')
    code_length = 12
    
    for org in SchoolGroup.objects.filter(access_code__isnull=True):
        max_attempts = 100
        code = None
        
        for _ in range(max_attempts):
            candidate_code = ''.join(random.choice(characters) for _ in range(code_length))
            # Check if code already exists
            if not SchoolGroup.objects.filter(access_code=candidate_code).exists():
                code = candidate_code
                break
        
        if code:
            now = timezone.now()
            org.access_code = code
            org.access_code_generated_at = now
            org.access_code_expires_at = now + timedelta(days=30)
            org.save(update_fields=['access_code', 'access_code_generated_at', 'access_code_expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('schoolgroups', '0003_alter_schoolgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgroup',
            name='access_code',
            field=models.CharField(blank=True, help_text='Randomly generated access code for joining this organization', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='access_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the access code expires (default: 30 days from generation)', null=True),
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='access_code_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the access code was generated', null=True),
        ),
        migrations.RunPython(generate_access_code_for_existing_orgs, migrations.RunPython.noop),
    ]
