# Generated by Django 4.2.27 on 2026-01-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolgroups', '0004_add_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgroup',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, help_text='When the current subscription period ends', null=True),
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='subscription_status',
            field=models.CharField(blank=True, help_text='Current subscription status from Stripe', max_length=50, null=True),
        ),
    ]
