# Generated by Django 4.2.27 on 2026-01-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolgroups', '0004_add_access_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', help_text='Current status of the chat', max_length=20)),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When chat was escalated to ticket', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When chat was marked as resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin assigned to this chat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('school_group', models.ForeignKey(help_text='Organization this chat belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='schoolgroups.schoolgroup')),
                ('user', models.ForeignKey(help_text='User who created the chat', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('ai', 'AI')], help_text='Type of sender (user, admin, or AI)', max_length=10)),
                ('content', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(help_text='Chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat')),
                ('sender', models.ForeignKey(blank=True, help_text='User who sent the message (null for AI messages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat', 'created_at'], name='chats_chatm_chat_id_454977_idx'), models.Index(fields=['chat', 'is_read'], name='chats_chatm_chat_id_847b08_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'status'], name='chats_chat_user_id_270988_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['school_group', 'status'], name='chats_chat_school__59bac7_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['assigned_to', 'status'], name='chats_chat_assigne_491414_idx'),
        ),
    ]
